name: Check cloning the source trees

on:
    push:
    pull_request:
    schedule:
      - cron: '0 0 * * *'
    workflow_dispatch:

jobs:
    check_clone:
        runs-on: ubuntu-latest
        env:
            ANONYMOUS: 1
        steps:
            - uses: actions/checkout@v4

            - name: run update.sh
              run:  ./update.sh
